"""Render a generated short/long fixture in an owned Resolve project; never reopen user projects."""
import argparse
import json
import os
from pathlib import Path
import sys
import time
import uuid
import math

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--script-lib', required=True)
parser.add_argument('--output', required=True, type=Path)
parser.add_argument('--timeline-frames', type=int, default=4096)
args = parser.parse_args()
args.output = args.output.resolve()
args.output.mkdir(parents=True, exist_ok=True)
os.environ['RESOLVE_SCRIPT_LIB'] = args.script_lib
os.environ['OPENCV_IO_ENABLE_OPENEXR'] = '1'
sys.path.insert(0, str(Path(os.environ['PROGRAMDATA']) / 'Blackmagic Design/DaVinci Resolve/Support/Developer/Scripting/Modules'))
import DaVinciResolveScript as dvr
import cv2
import numpy as np
from PIL import Image

resolve = dvr.scriptapp('Resolve')
if resolve is None:
    raise RuntimeError('Start an owned headless Resolve session before running this test')
pm = resolve.GetProjectManager()
previous = pm.GetCurrentProject()
previous_name = previous.GetName() if previous else None
if previous_name and not previous_name.startswith('DLSS5_040_r1_host_test_') and previous_name != 'Untitled':
    raise RuntimeError('Use a blank owned Resolve session; a user project is currently open')
project_name = 'DLSS5_040_r1_host_test_' + uuid.uuid4().hex[:8]
project = pm.CreateProject(project_name)
if project is None:
    raise RuntimeError('Failed to create a separate test project')
result = {'HostVersion': resolve.GetVersionString(), 'TestProject': project_name,
          'PreviousProject': previous_name, 'UserProjectSaveRequested': False,
          'Source': 'Deterministic pattern generated by this script; no external media'}
def await_true(operation, message, timeout=5):
    deadline = time.monotonic()+timeout
    while time.monotonic()<deadline:
        if operation():
            return
        time.sleep(0.1)
    raise RuntimeError(message)
try:
    for key, value in {'timelineResolutionWidth': '640', 'timelineResolutionHeight': '360',
                       'timelineFrameRate': '24'}.items():
        assert project.SetSetting(key, value), key
    rng = np.random.default_rng(20261003)
    y, x = np.mgrid[:360, :640]
    base = np.stack((0.1 + 0.8*x/639, 0.1 + 0.8*y/359,
                     0.3 + 0.2*np.sin(x/7) * np.cos(y/5)), axis=-1)
    pixels = np.clip(base + rng.normal(0, 0.025, base.shape), 0, 1)
    fixture = args.output / 'generated-source.png'
    Image.fromarray(np.rint(pixels*255).astype(np.uint8)).save(fixture)
    pool = project.GetMediaPool()
    media = pool.ImportMedia([str(fixture)])
    assert media, 'Generated fixture import failed'
    source_fps = float(media[0].GetClipProperty('FPS') or project.GetSetting('timelineFrameRate'))
    timeline_fps = float(project.GetSetting('timelineFrameRate'))
    source_frames = math.ceil(args.timeline_frames * source_fps / timeline_fps)
    result['SourceFPS'] = source_fps
    result['TimelineFPS'] = timeline_fps
    timeline = pool.CreateTimelineFromClips('DLSSNR acceptance', [
        {'mediaPoolItem': media[0], 'startFrame': 0, 'endFrame': source_frames}])
    assert timeline is not None
    assert project.SetCurrentTimeline(timeline)
    # A newly created headless timeline may not yet have a usable current-clip
    # context. Reload only our saved test project before attaching Fusion.
    assert pm.SaveProject()
    assert pm.CloseProject(project)
    project = pm.LoadProject(project_name)
    assert project is not None
    timeline = project.GetCurrentTimeline()
    assert timeline is not None
    assert resolve.OpenPage('edit')
    await_true(lambda: timeline.SetCurrentTimecode(timeline.GetStartTimecode()), 'Timeline positioning failed')
    clips = timeline.GetItemListInTrack('video', 1)
    assert len(clips) == 1
    result['TimelineFrames'] = clips[0].GetDuration()
    assert result['TimelineFrames'] >= args.timeline_frames, 'Host did not create the long still-image clip'
    codecs = project.GetRenderCodecs('exr')
    codec = next((v for k, v in codecs.items() if 'RGBA' in k and 'Float' in k), None)
    codec = codec or next(iter(codecs.values()))
    assert project.SetCurrentRenderFormatAndCodec('exr', codec)
    assert project.SetCurrentRenderMode(1)
    result['RenderMode'] = project.GetCurrentRenderMode()

    def render(name, offset=0, count=2):
        directory = args.output / name
        directory.mkdir(exist_ok=True)
        assert project.SetRenderSettings({'TargetDir': str(directory), 'CustomName': name,
            'SelectAllFrames': False, 'MarkIn': timeline.GetStartFrame()+offset,
            'MarkOut': timeline.GetStartFrame()+offset+count-1, 'ExportVideo': True, 'ExportAudio': False})
        job = project.AddRenderJob()
        assert job, 'No render job returned'
        assert project.StartRendering([job]), 'Render did not start'
        deadline = time.monotonic()+90
        while project.IsRenderingInProgress():
            if time.monotonic() > deadline:
                project.StopRendering()
                raise RuntimeError('Test render exceeded 90 seconds; stopped our job')
            time.sleep(0.25)
        status = project.GetRenderJobStatus(job)
        result[name+'Job'] = status
        # JobStatus is localized by Resolve (the native bridge can also emit
        # undecodable text). Validate completion and actual EXR payloads below.
        assert status.get('CompletionPercentage') == 100, str(status)
        assert not status.get('Error'), str(status)
        files = sorted(directory.glob('*.exr'))
        assert len(files) == count, f'{name}: expected {count} EXR frames, got {len(files)}'
        frames = [cv2.imread(str(p), cv2.IMREAD_UNCHANGED) for p in files]
        assert all(f is not None and f.shape[:2] == (360, 640) and np.isfinite(f).all() for f in frames)
        print(name, 'rendered', len(files), 'finite EXR frames', flush=True)
        return frames

    baseline = render('baseline')
    assert resolve.OpenPage('edit')
    await_true(lambda: timeline.SetCurrentTimecode(timeline.GetStartTimecode()), 'Fusion positioning failed')
    assert resolve.OpenPage('fusion')
    # Opening Fusion creates Composition 1 automatically. Editing a newly added
    # Composition 2 would leave the active output unchanged.
    comp = clips[0].GetFusionCompByIndex(1) if clips[0].GetFusionCompCount() else clips[0].AddFusionComp()
    assert comp is not None
    comp_names = clips[0].GetFusionCompNameList()
    assert comp_names, 'No attached Fusion composition'
    comp = clips[0].LoadFusionCompByName(comp_names[0])
    assert comp is not None
    comp.Lock()
    try:
        tools = comp.GetToolList(False)
        source = next(t for t in tools.values() if t.GetAttrs().get('TOOLS_RegID') == 'MediaIn')
        output = next(t for t in tools.values() if t.GetAttrs().get('TOOLS_RegID') == 'MediaOut')
        nr = comp.AddTool('ofx.com.saog.resolve.dlss5')
        assert nr is not None
        assert nr.ConnectInput('Source', source)
        assert output.ConnectInput('Input', nr)
        nr.SetInput('nrPassCount', 1)
        nr.SetInput('nrSkinStructure', 0)
    finally:
        comp.Unlock()
    result['FusionCompCount'] = clips[0].GetFusionCompCount()
    result['FusionCompNames'] = clips[0].GetFusionCompNameList()
    result['CompAttrs'] = {k:v for k,v in comp.GetAttrs().items() if k.startswith(('COMPN_', 'COMPS_'))}
    comp_path = args.output / 'test-fusion.comp'
    assert clips[0].ExportFusionComp(str(comp_path), 1), 'Test comp was not attached to the timeline item'
    assert resolve.OpenPage('deliver')
    assert pm.SaveProject(), 'Failed to persist our test graph'
    processed = render('nr-two-pass')
    difference = max(float(np.max(np.abs(a-b))) for a, b in zip(baseline, processed))
    result['NrMaximumDifference'] = difference
    assert difference > 1e-6, 'Fusion effect was not applied or yielded a zero correction; do not claim NR acceptance'
    nr.SetInput('nrResidualStrength', 0)
    identity = render('strength-zero')
    identity_error = max(float(np.max(np.abs(a-b))) for a, b in zip(baseline, identity))
    result['ZeroStrengthMaximumError'] = identity_error
    assert identity_error <= 1e-6, 'Zero-strength export changed the original image'
    nr.SetInput('nrResidualStrength', 1)
    late = render('nr-cold-jump', offset=args.timeline_frames-2, count=1)
    result['ColdJumpFrameOffset'] = args.timeline_frames-2
    result['ColdJumpFinite'] = bool(np.isfinite(late[0]).all())
    result['Passed'] = True
    pm.SaveProject()
except Exception as error:
    result['Passed'] = False
    result['Error'] = str(error)
    raise
finally:
    (args.output / 'host-render-evidence.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
    # Reopening the previous user project can immediately trigger its effects.
    # Leave only our test project closed; never call LoadProject here.
    pm.CloseProject(project)
